### ISSUE TITLE
thockin/kubectl-sidecar:v1.30.0-1 not publically available on Docker-hub

### ISSUE THREAD

**Issue by Kapil987** [thockin/kubectl-sidecar#2]
The image thockin/kubectl-sidecar:v1.30.0-1 is not publically visible to be ustilised. it may have been private.  this results in Error: ErrImagePull

Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  23s               default-scheduler  Successfully assigned default/demo-kubectl-sidecar-5d56678585-ndcxr to demo-worker2
  Normal   BackOff    21s               kubelet            Back-off pulling image "thockin/kubectl-sidecar:v1.30.0-1"
  Warning  Failed     21s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    7s (x2 over 23s)  kubelet            Pulling image "thockin/kubectl-sidecar:v1.30.0-1"
  Warning  Failed     5s (x2 over 21s)  kubelet            Failed to pull image "thockin/kubectl-sidecar:v1.30.0-1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/thockin/kubectl-sidecar:v1.30.0-1": failed to resolve reference "docker.io/thockin/kubectl-sidecar:v1.30.0-1": docker.io/thockin/kubectl-sidecar:v1.30.0-1: not found
  Warning  Failed     5s (x2 over 21s)  kubelet            Error: ErrImagePull

![dockerhub](https://github.com/user-attachments/assets/e59a18d6-0040-48ad-9c74-879cdeb80ca5)

Possible Solution: We need to either switch to the older version or make the newer version visible.

Thanks

**Comment by thockin** [comment]
I can update the example, but note that it was not my intention to provide constantly updated images for free from my personal registry repo :)

This git repo is an example for you to build your own :)

Update now.
